name: CI

on:
    pull_request:
        branches: ["main"]

jobs:
    pipes:
        uses: dragunovartem99/pipes/.github/workflows/ci-node.yaml@v3.0.0
        with:
            checks: '["format:check", "types:check", "lint:check", "test", "build"]'
