name: CI

on:
    pull_request:
        branches: ["main"]

jobs:
    pipes:
        uses: dragunovartem99/pipes/.github/workflows/ci.yaml@main
        with:
            checks: '["format:check", "types:check", "lint:check", "test"]'
