name: Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    pipes:
        uses: dragunovartem99/pipes/.github/workflows/deploy-github.yaml@v3.1.0
        with:
            setup: node
            build: npm run build
            dist-folder: ./dist
