name: Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    pipes:
        uses: dragunovartem99/pipes/.github/workflows/deploy-github.yaml@v1.3.0
        with:
            build-command: build
            dist-folder: ./dist
