name: Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml

    pipes:
        needs: ci
        uses: dragunovartem99/pipes/.github/workflows/deploy-github.yaml@v1.0.1
        with:
            build-command: build
            dist-folder: ./dist
